version: '3.8'

services:

  bedrock:
    image: itzg/minecraft-bedrock-server:latest@sha256:c4c7f67189d7915e1f1410d9e20affc4deb25df62df543a9424fe2487ffb2b51
    ports:
      - target: 19132
        published: 19132
        protocol: udp
        mode: host
    networks:
      - host
    volumes:
      - server-data:/data
    environment:
      # docker image properties
      - EULA=TRUE          # accept the microsoft eula
      - VERSION=LATEST     # LATEST|PREVIOUS|major.minor|major.minor.patch.release
      # Minecraft server.properties parameters
      # https://minecraft.fandom.com/wiki/Server.properties#Bedrock_Edition_3
      - "SERVER_NAME=Family Server"
      - "LEVEL_NAME=Mushroom Kingdom"
      - GAMEMODE=survival
      - DIFFICULTY=easy
      - ONLINE_MODE=false
      #- ALLOW_CHEATS=false
      #- ALLOW_LIST=xxx
      #- DEFAULT_PLAYER_PERMISSION_LEVEL=member
      #- LEVEL_SEED=xxx
      #- LEVEL_TYPE=Default
      #- MAX_PLAYERS=10
      #- MAX_THREADS=8
      #- PLAYER_IDLE_TIMEOUT=30
      #- PLAYER_MOVEMENT_SCORE_THRESHOLD=20
      #- PLAYER_MOVEMENT_DISTANCE_THRESHOLD=0.3
      #- PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS=500
      #- SERVER_AUTHORITATIVE_MOVEMENT=server-auth
      #- SERVER_PORT=19132
      #- SERVER_PORT_V6=19133
      #- TEXTUREPACK_REQUIRED=false
      #- TICK_DISTANCE=4
      #- VIEW_DISTANCE=32
      #- CORRECT_PLAYER_MOVEMENT=false
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86_64

  backup:
    image: alpinelinux/docker-cli@sha256:6cad65650ed9c4cd9c818073b00c692a17cb0997578838e6f3bb5fca67b0871d
    entrypoint: "sh -c"
    command: |
      '
      DATE_FMT="%Y-%m-%d_%H-%M-%S"

      echo "Stopping bedrock service..."
      docker service scale $$SERVICE_NAME=0 > /dev/null

      for world_dir in /opt/server/worlds/*; do
        world_name=$$(basename "$$world_dir")
        now=$$(date +$$DATE_FMT)
        target="/opt/backups/$$world_name-$$now.tar.gz"
        echo "Backing up '$$world_name' to $$target..."
        tar -cpzf "$$target" -C "$$world_dir" .

        echo "Cleaning up old versions of '$$world_name'..."
        find /opt/backups -name "$$world_name-*.tar.gz" -type f -mtime +14 -print -delete
      done

      echo "Starting bedrock service..."
      docker service scale $$SERVICE_NAME=1 > /dev/null
      '
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - server-data:/opt/server
      - backups-data:/opt/backups
    environment:
      # assumes this is deployed to a stack named "mc"
      - SERVICE_NAME=mc_bedrock
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: none
      replicas: 0 # none by default; created when cron hits
      labels:
        # backup and restart daily at 6am
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0 6 * * *

  update:
    image: alpinelinux/docker-cli@sha256:6cad65650ed9c4cd9c818073b00c692a17cb0997578838e6f3bb5fca67b0871d
    entrypoint: "sh -c"
    command: |
      '
      # force service update, which causes restart
      docker service update $$SERVICE_NAME --force
      '
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # assumes this is deployed to a stack named "mc"
      - SERVICE_NAME=mc_bedrock
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: none
      replicas: 0 # none by default; created when cron hits
      labels:
        # restart daily at 6am to get latest MC version
        - swarm.cronjob.enable=false
        - swarm.cronjob.schedule=0 6 * * *

  cron:
    image: crazymax/swarm-cronjob:1.12.0
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=info
      - LOG_JSON=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 0 # disabled; already running in lab stack

networks:
  host:
    external: true

volumes:
  server-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/apps/minecraft/server'
  backups-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/apps/minecraft/backups'
